# Site settings
title: "Forge ML"
author: "Jake Zegil"
baseurl: ""
url: "https://forge-ml.com"
date_format: "%B %-d, %Y"

# Features
features:
  related_posts: true
  post_footers: true
  subscribe_cta: true
  social_icons: true
  contact_form:
    ajaxify: false
  mathjax: false
  extended_fonts: false
  anchorjs: true

# Social media
social:
  github: "forge-ml"
  twitter: "ml_forge"

# Localization
text:
  pagination:
    newer: "← Newer"
    older: "Older →"
  post:
    updated: "Last updated"
    reading_time: "minute read"
    related: "You might also enjoy"
  index:
    coming_soon: "Exciting content coming soon..."
  locale: "en_US"

# Build configuration
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: pretty
paginate: 12
paginate_path: "/blog/page/:num/"
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude: 
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

# Content collections
collections_dir: collections
collections:
  reviews:
    output: true
    permalink: /reviews/:name/
  portfolio:
    output: true
    permalink: /portfolio/:name/